modLoader="javafml"
loaderVersion="[40,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/ApexStudios-Dev/FantasyDice/issues"

[[mods]]
	modId="fantasydice"
	version="${file.jarVersion}"
	displayName="Fantasy's Dice"
	updateJSONURL="https://raw.githubusercontent.com/ApexStudios-Dev/Version/master/fantasydice.json"
	displayURL="https://www.apexstudios.dev/fantasys-dice"
	logoFile="banner.png"
	credits="Apex - Programming, FantasyGaming - Artist"
	authors="ApexStudios"
	description="Adds various Dungeons & Dragons inspired Dice to the game"

[[dependencies.fantasydice]]
	modId="forge"
	mandatory=true
	versionRange="[40.1.60,41)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.fantasydice.custom.mc-publish]
		ignore=true
[[dependencies.fantasydice]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.18.2,1.19)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.fantasydice.custom.mc-publish]
		ignore=true
[[dependencies.fantasydice]]
	modId="apexcore"
	mandatory=false
	versionRange="[4.11.0,5.0.0)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.fantasydice.custom.mc-publish]
		modrinth="apexcore"
		curseforge="apexcore"
[[dependencies.fantasydice]]
	modId="commonality"
	mandatory=true
	versionRange="[1.3.0,2.0.0)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.fantasydice.custom.mc-publish]
		ignore=true
[[dependencies.fantasydice]]
	modId="jei"
	mandatory=false
	versionRange="[10.1.3.+,)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.fantasydice.custom.mc-publish]
		curseforge="jei"