modLoader="javafml"
loaderVersion="[36,)"
license="GNU"
issueTrackerURL="https://github.com/ApexModder/FantasyTable/issues"

[[mods]]
modId="fantasytable"
version="${file.jarVersion}"
displayName="Fantasy's Tabletop"
# updateJSONURL="https://raw.githubusercontent.com/ApexModder/DiceMod/main/update.json"
# displayURL="https://www.curseforge.com/minecraft/mc-mods/dicemod"
# logoFile="logo.png"
credits="ApexSPG (ApexModder) - Programming, Testing\nFantasyGaming - Mod Requester, Textures, Testing\nTobiSPG - Testing\nTTerrag - Registrate\n\n"
authors="ApexModder, FantasyGaming"
description="Tabletop mod which adds various Tabletop esque elements into the game.\nThis mod was requested by FantasyGaming.\n\nThis mod makes use of Registrate and comes with a version repackaged under `xyz.apex.forge.fantasytable.repack.repack.com.tterrag.registrate`."

[[dependencies.fantasytable]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.fantasytable]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17]"
    ordering="NONE"
    side="BOTH"