modLoader="javafml"
loaderVersion="[44,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://discord.apexstudios.dev/"

[[mods]]
	modId="fantasydice"
	version="${file.jarVersion}"
	displayName="Fantasy's Dice"
	updateJSONURL="https://api.modrinth.com/updates/fantasy-dice/forge_updates.json"
	displayURL="https://www.apexstudios.dev/fantasys-dice"
	logoFile="banner.png"
	credits="Apex - Programming, FantasyGaming - Artist"
	authors="ApexStudios"
	description="Adds various Dungeons & Dragons inspired Dice to the game"

[[dependencies.fantasydice]]
	modId="forge"
	mandatory=true
	versionRange="[44.0.0,45.0.0)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.fantasydice.custom.mc-publish]
		ignore=true
[[dependencies.fantasydice]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.19.3,1.19.4)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.fantasydice.custom.mc-publish]
		ignore=true
[[dependencies.fantasydice]]
	modId="commonality"
	mandatory=true
	versionRange="[5.0.0,6.0.0)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.fantasydice.custom.mc-publish]
		ignore=true
[[dependencies.fantasydice]]
	modId="apexcore"
	mandatory=true
	embedded=true
	versionRange="[8.0.0,9.0.0)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.fantasydice.custom.mc-publish]
		modrinth="apexcore"
		curseforge="apexcore"
[[dependencies.fantasydice]]
	modId="jei"
	mandatory=false
	versionRange="[12.0.0.0,)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.fantasydice.custom.mc-publish]
		curseforge="jei"
