modLoader="javafml"
loaderVersion="[36,)"
license="GNU"
# issueTrackerURL="https://github.com/ApexModder/DiceMod/issues"

[[mods]]
modId="fantasytable"
version="${file.jarVersion}"
displayName="Fantasy's TableTop"
# updateJSONURL="https://raw.githubusercontent.com/ApexModder/DiceMod/main/update.json"
# displayURL="https://www.curseforge.com/minecraft/mc-mods/dicemod"
# logoFile="logo.png"
credits="ApexSPG (ApexModder) - Programming, Testing\nFantasyGaming - Mod Requester, Textures, Testing\nTobiSPG - Testing\nTTerrag - Registrate\n\n"
authors="ApexModder, FantasyGaming"
description="TableTop mod requested by a friend (FantasyGaming).\nThis mod adds various tabletop elements into the game from a variety of dice to playing cards and even board games.\n\nThis mod makes use of Registrate and comes with a version repackaged under `xyz.apex.forge.fantasytable.repack.repack.com.tterrag.registrate`.\n"

[[dependencies.dicemod]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dicemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17]"
    ordering="NONE"
    side="BOTH"